name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('requirements.txt', 'requirements-dev.txt') }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Run ruff
        run: ruff check .
      - name: Run black
        run: black --check .
      - name: Run isort
        run: isort --check-only .
      - name: Type check
        run: mypy src || true
        shell: bash
      - name: Run tests
        run: pytest -q -m "not integration"
      - name: Upload reports
        if: ${{ hashFiles('reports/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/
